-- MySQL Script generated by MySQL Workbench
-- Fri Nov 23 15:29:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pdv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pdv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pdv` DEFAULT CHARACTER SET utf8 ;
USE `db_pdv` ;

-- -----------------------------------------------------
-- Table `db_pdv`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pdv`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cnpj/cpf` CHAR(18) NOT NULL,
  `phone` CHAR(14) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pdv`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pdv`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cpf/cnpj` CHAR(18) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_companies_idx` (`companies_id` ASC),
  CONSTRAINT `fk_clients_companies`
    FOREIGN KEY (`companies_id`)
    REFERENCES `db_pdv`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pdv`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pdv`.`contributors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `phone` CHAR(14) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `salary` FLOAT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `companie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contributors_companies1_idx` (`companie_id` ASC),
  CONSTRAINT `fk_contributors_companies1`
    FOREIGN KEY (`companie_id`)
    REFERENCES `db_pdv`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;